### ISSUE TITLE
TypeError: transport is not a function

### ISSUE THREAD

**Issue by brandonros** [winstonjs/winston-loggly#42]
log.js

```
var winston = require('winston');

require('winston-loggly');

winston.add(winston.transports.Loggly, {
	token: 'revoked',
	subdomain: 'revoked',
	tags: ['Winston-NodeJS'],
	json: true
});

module.exports = function (level, msg, metadata) {
	winston.log(level, msg, metadata);
};
```

Stack
```
TypeError: transport is not a function
     at Logger.add (/home/brandon//node_modules/winston/lib/winston/logger.js:475:41)
     at Object.winston.(anonymous function) [as add] (/home/brandon/node_modules/winston/lib/winston.js:87:34)
     at Object.<anonymous> (/home/api_server/lib/log.js:5:9)
```

I can't reproduce this on my development machine, but can reproduce it on my production servers.

**Comment by jcrugzz** [comment]
@brandonros can you identify if there is a different version of `winston` or `winston-loggly` in dev compared to production?

**Comment by brandonros** [comment]
There is not. I can 'ncu -a' and 'npm update' on both.

**Comment by jcrugzz** [comment]
@brandonros try `rm -rf node_modules/winston && rm -rf node_modules/winston-loggly && npm i` to ensure its updating as expected

**Comment by brandonros** [comment]
```
brandon@server:~/skulabs$ rm -rf node_modules/winston && rm -rf node_modules/winston-loggly && npm i
server@1.0.0 /home/brandon/server
├─┬ winston@2.2.0
│ ├── async@1.0.0
│ └── colors@1.0.3
└── winston-loggly@1.3.1
```

```
brandon@server:~/skulabs$ node api_server/api_server.js
/home/brandon/server/node_modules/winston/lib/winston/logger.js:475
  var instance = created ? transport : (new (transport)(options));
                                        ^

TypeError: transport is not a function
    at Logger.add (/home/brandon/server/node_modules/winston/lib/winston/logger.js:475:41)
    at Object.winston.(anonymous function) [as add] (/home/brandon/server/node_modules/winston/lib/winston.js:87:34)
    at Object.<anonymous> (/home/brandon/server/lib/log.js:5:9)
```

**Comment by brandonros** [comment]
It has something to do with me being a noob when it comes to module.exports and its behavior/caching, I think.

**Comment by tomarsamar** [comment]
@brandonros try using logger = require('morgan')  along with winston, I am facing same problem if I remove morgan

**Comment by kblcuk** [comment]
@brandonros did you manage to solve this? Seeing the same issue. :/

**Comment by kblcuk** [comment]
...found it out by myself eventually -- reason was in two different versions of `winston` library that npm decided to install: root `node_modules` had 2.1.1 version, and local had latest 2.2.0:
```
$ find . -type d -name winston
./node_modules/logger/node_modules/winston <-- my own logging module
<skip>
./node_modules/winston
```

Due to that and some require magic I don't quite understand, transport set by `winston-loggly` got set on a different instance of `winston` (root one) than the one used to set transport (in "logger")
the root one was installed due to [prompt](https://github.com/flatiron/prompt) module explicitly requiring 2.1.x.

So in my case the "fix" was to explicitly require latest winston at the root of the package, which would then re-shuffle winston deps (storing local version in prompt rather than in root).

Hope this helps.

**Comment by lucaszanella** [comment]
Having the same problem as brandonros. When I place the code at index.js, everything runs, but when I place it in a module and require the module in index.js, I get the same error

**Comment by RobAWilkinson** [comment]
@lucaszanella I am getting the same issue as you, did you ever find a fix?

**Comment by AnthonyReid99** [comment]
Anybody ever solve this?

**Comment by yauri-io** [comment]
I solved this by removing 'winston' and 'winston-loggly-bulk'
Then re-install 'winston' and 'winston-loggly-bulk' accordingly.

Before I was installing winston-loggly-bulk first then winston. Not sure if it is the issue.
